export const TRUTHS = {
  'The Host': [
    "What's the most embarrassing thing that happened to you in public? 😳",
    "What's your biggest fear and why? 😰",
    "What's the worst lie you've ever told? 🤥",
    "What's your most irrational fear? 😱",
    "What's the most trouble you've ever been in? 😅",
    "What's your biggest regret? 😔",
    "What's the most embarrassing thing in your search history? 🔍",
    "What's your biggest insecurity? 😟",
    "What's the worst thing you've ever done to someone? 😈",
    "What's your biggest secret that no one knows? 🤫",
    "What's the most ridiculous thing you've ever done to avoid doing homework? 📚",
    "What's your most embarrassing childhood nickname and how did you get it? 🧒",
    "What's the weirdest food combination you actually enjoy eating? 🍕",
    "What's the most embarrassing thing you've ever said to a teacher or boss? 😅",
    "What's your biggest guilty pleasure TV show or movie? 📺",
    "What's the most ridiculous thing you've ever bought on impulse? 🛒",
    "What's your most embarrassing fashion choice from the past? 👗",
    "What's the weirdest dream you've ever had that you still remember? 💭",
    "What's the most embarrassing thing you've ever done to impress someone? 😳",
    "What's your biggest pet peeve that drives you crazy? 😤",
    "What's the most ridiculous thing you've ever done to avoid socializing? 🚪",
    "What's your most embarrassing karaoke moment? 🎤",
    "What's the weirdest thing you've ever eaten just to try it? 🤢",
    "What's the most embarrassing thing you've ever done while trying to be cool? 😎",
    "What's your biggest fear about being in public? 😰",
    "What's the most ridiculous thing you've ever done to avoid exercise? 🏃‍♂️",
    "What's your most embarrassing moment from a family gathering? 👨‍👩‍👧‍👦",
    "What's the weirdest thing you've ever done to entertain yourself when bored? 🤪",
    "What's the most embarrassing thing you've ever done to avoid confrontation? 😶",
    "What's your biggest secret about your daily routine? 🤫",
    "What's the most ridiculous thing you've ever done to avoid doing dishes? 🍽️",
    "What's the most embarrassing thing you've ever done to avoid going to the gym? 💪",
    "What's your weirdest habit that you're secretly proud of? 🤫",
    "What's the most ridiculous thing you've ever done to impress your crush? 😍",
    "What's your most embarrassing moment from a school presentation? 🎓",
    "What's the weirdest thing you've ever done to avoid making a phone call? 📱",
    "What's your biggest secret about your eating habits? 🍕",
    "What's the most embarrassing thing you've ever done to avoid doing laundry? 👕",
    "What's your weirdest fear that you know is completely irrational? 😱",
    "What's the most ridiculous thing you've ever done to avoid cleaning your room? 🧹",
    "What's your most embarrassing moment from a job interview? 💼",
    "What's the weirdest thing you've ever done to entertain your pets? 🐾",
    "What's your biggest secret about your morning routine? ☀️",
    "What's the most embarrassing thing you've ever done to avoid going to bed? 😴",
    "What's your weirdest talent that you've never told anyone about? 🎭",
    "What's the most ridiculous thing you've ever done to avoid cooking? 👨‍🍳",
    "What's your most embarrassing moment from a first date? 💕",
    "What's the weirdest thing you've ever done to avoid doing taxes? 📊",
    "What's your biggest secret about your shopping habits? 🛍️",
    "What's the most embarrassing thing you've ever done to avoid going to the doctor? 🏥",
    "What's your weirdest superstition that you still believe in? 🔮",
    "What's the most ridiculous thing you've ever done to avoid doing yard work? 🌱",
    "What's the most embarrassing thing you've ever done to avoid going to a party? 🎉",
    "What's your weirdest habit when you're home alone? 🏠",
    "What's the most ridiculous thing you've ever done to avoid doing your taxes? 📊",
    "What's your most embarrassing moment from a video call? 📹",
    "What's the weirdest thing you've ever done to avoid doing the dishes? 🍽️",
    "What's your biggest secret about your Netflix watching habits? 📺",
    "What's the most embarrassing thing you've ever done to avoid going to the dentist? 🦷",
    "What's your weirdest fear about technology? 💻",
    "What's the most ridiculous thing you've ever done to avoid doing laundry? 👕",
    "What's your most embarrassing moment from a group chat? 💬",
    "What's the weirdest thing you've ever done to avoid going to bed early? 😴",
    "What's your biggest secret about your music taste? 🎵",
    "What's the most embarrassing thing you've ever done to avoid going to the gym? 💪",
    "What's your weirdest habit when you're stressed? 😰",
    "What's the most ridiculous thing you've ever done to avoid doing homework? 📚",
    "What's your most embarrassing moment from a family dinner? 🍽️",
    "What's the weirdest thing you've ever done to avoid doing chores? 🧹",
    "What's your biggest secret about your social media habits? 📱",
    "What's the most embarrassing thing you've ever done to avoid going to a meeting? 💼",
    "What's your weirdest superstition about food? 🍕",
    "What's the most ridiculous thing you've ever done to avoid doing your hair? 💇‍♀️",
    "What's your most embarrassing moment from a group project? 👥",
    "What's the weirdest thing you've ever done to avoid doing your makeup? 💄",
    "What's your biggest secret about your shopping addiction? 🛍️",
    "What's the most embarrassing thing you've ever done to avoid going to a wedding? 💒",
    "What's your weirdest habit when you're cooking? 👨‍🍳",
    "What's the most ridiculous thing you've ever done to avoid doing your nails? 💅",
    "What's your most embarrassing moment from a Zoom meeting? 🖥️",
    "What's the weirdest thing you've ever done to avoid doing your skincare routine? 🧴",
    "What's your biggest secret about your gaming habits? 🎮",
    "What's the most embarrassing thing you've ever done to avoid going to a reunion? 👨‍👩‍👧‍👦",
    "What's your weirdest fear about social media? 📱",
    "What's the most ridiculous thing you've ever done to avoid doing your taxes? 📊",
    "What's your most embarrassing moment from a group presentation? 🎤",
    "What's the weirdest thing you've ever done to avoid doing your hair? 💇‍♀️",
    "What's your biggest secret about your reading habits? 📚",
    "What's the most embarrassing thing you've ever done to avoid going to a funeral? ⚰️",
    "What's your weirdest habit when you're bored? 😴",
    "What's the most ridiculous thing you've ever done to avoid doing your makeup? 💄",
    "What's your most embarrassing moment from a family vacation? 🏖️",
    "What's the weirdest thing you've ever done to avoid doing your laundry? 👕",
    "What's your biggest secret about your exercise habits? 🏃‍♂️",
    "What's the most embarrassing thing you've ever done to avoid going to a doctor? 🏥",
    "What's your weirdest superstition about money? 💰",
    "What's the most ridiculous thing you've ever done to avoid doing your homework? 📚",
    "What's your most embarrassing moment from a group chat? 💬",
    "What's the weirdest thing you've ever done to avoid doing your chores? 🧹",
    "What's your biggest secret about your dating app habits? 💕"
  ],
  // 'Just a Chill Guy': [
  //   "What's your favorite way to spend a lazy Sunday? 😴",
  //   "What's the most random thing you've ever done? 🤪",
  //   "What's your guilty pleasure TV show? 📺",
  //   "What's the weirdest food combination you actually enjoy? 🍕",
  //   "What's your most embarrassing childhood memory? 🧒",
  //   "What's the strangest dream you've ever had? 💭",
  //   "What's your biggest pet peeve? 😤",
  //   "What's the most ridiculous thing you've ever bought? 🛒",
  //   "What's your favorite comfort food? 🍜",
  //   "What's the most embarrassing thing you've ever said to someone? 😅"
  // ],
  'Influencer': [
    "What's your biggest heartbreak story? 💔",
    "What's the most romantic thing someone has ever done for you? 💕",
    "What's your favorite love song and why? 🎵",
    "What's your biggest relationship regret? 😔",
    "What's the most dramatic thing you've ever done for love? 🌹",
    "What's your biggest fear about relationships? 😰",
    "What's the most embarrassing thing you've done to impress someone? 😳",
    "What's your biggest relationship lesson learned? 📚",
    "What's the most romantic thing you've ever done for someone? 💝",
    "What's your biggest relationship insecurity? 😟",
    "✨ Tell me about a time you used a cheesy pickup line that actually worked. I'm taking notes!",
  "💖 What's the most romantic thing you've ever done for someone? I bet it's a story that makes hearts melt.",
  "🤳 What's a compliment you've received that you still think about? It clearly had an impact!",
  "🤫 Spill the tea! What's a secret crush you've had on someone in real life? Don't be shy!",
  "😭 Who is a person you were smitten with but never got a chance to talk to? We can send them a smoke signal!",
  "🤔 Describe the most embarrassing romantic text you've ever accidentally sent to the wrong person. We want the full story!",
  "💸 What's the most impulsive thing you've ever done to get someone's attention?",
  "👀 What is the most memorable date you've ever been on, good or bad? Let's hear the details!",
  "😂 What is the one thing you do when you have a crush on someone? Is it subtle or totally obvious?",
  "🥺 What is the most romantic movie you've ever seen that has made you cry?",
  "💅 What is the most romantic song on your playlist right now? Don't be shy!",
  "😲 Reveal a secret talent or a weird skill you have that your crush would never expect.",
  "🏡 Who is a celebrity you would love to go on a date with and why?",
  "😬 What is the most embarrassing thing you've ever done to impress someone?",
  "🌟 What is a romantic gesture you've always wanted to do but have never had the chance to?",
  "🤯 What is one thing about you that people find surprisingly attractive?",
  "🗣️ Who in the room would you want to be your wingman or wingwoman and why? I have to know their tactics!",
  "💫 Who is a fictional character you would love to go on a date with? Tell me why they're your type!",
  "😅 What is the most random place you've ever met someone interesting?",
  "💔 Tell us about a time you tried to flirt with someone and it completely failed.",
  "🤔 What is the most common piece of romantic advice you receive that you completely ignore?",
  "💖 Share the most awkward romantic moment you've ever had. We love a good story time!",
  "🎬 What is one movie you would show on a first date?",
  "🥳 What is the most spontaneous thing you've ever done on a date?",
  "🤡 What is a romantic cliché you secretly love?",
  "🤩 What is the funniest memory you have with a significant other?",
  "😫 What is the worst 'bad advice' you've ever received about dating?",
  "🤩 If you had to switch lives with any fictional romantic character, who would it be?",
  "😎 What is the funniest thing you have ever overheard in a conversation about love?",
      "🤫 What's the most childish thing you still do when you have a crush on someone?",
    "What's the most amazing place you've ever traveled to and why was it unforgettable? ✈️",
    "What's your biggest travel disaster story that you can laugh about now? 😅",
    "What's the weirdest food you've ever tried while traveling? 🍜",
    "What's your most embarrassing moment from a vacation? 🏖️",
    "What's the most spontaneous trip you've ever taken? 🚗",
    "What's your biggest travel fear and how do you deal with it? 😰",
    "What's the most beautiful sunset or sunrise you've ever seen? 🌅",
    "What's your weirdest travel companion story? 👥",
    "What's the most expensive thing you've ever bought on impulse while traveling? 💰",
    "What's your biggest travel regret? 😔",
    "What's the most amazing local experience you've had while traveling? 🌍",
    "What's your weirdest accommodation story? 🏨",
    "What's the most embarrassing thing you've done to avoid paying for something? 😳",
    "What's your biggest travel goal that you haven't achieved yet? 🎯",
    "What's the most ridiculous thing you've ever packed for a trip? 🧳",
    "What's your most embarrassing moment from a business trip? 💼",
    "What's the weirdest thing you've ever done to save money while traveling? 💸",
    "What's your biggest travel pet peeve? 😤",
    "What's the most amazing wildlife encounter you've ever had? 🦁",
    "What's your weirdest travel superstition? 🔮",
    "What's the most embarrassing thing you've ever done to impress locals? 😅",
    "What's your biggest travel accomplishment that you're proud of? 🏆",
    "What's the most ridiculous thing you've ever done to avoid jet lag? 😴",
    "What's your most embarrassing moment from a road trip? 🚙",
    "What's the most amazing adventure you've ever had that changed your life? 🗺️",
    "What's your weirdest travel habit that you're secretly proud of? 🤫",
    "What's the most embarrassing thing you've ever done to avoid paying for a hotel? 🏨",
    "What's your biggest travel dream that you're working towards? 💭",
    "What's the most ridiculous thing you've ever done to avoid getting lost? 🧭",
    "What's your most embarrassing moment from a camping trip? ⛺",
    "What's the weirdest thing you've ever done to entertain yourself on a long flight? ✈️",
    "What's your biggest travel insecurity? 😟",
    "What's the most amazing cultural experience you've ever had? 🎭",
    "What's your weirdest travel ritual that you do before every trip? 🔮",
    "What's the most embarrassing thing you've ever done to avoid speaking a foreign language? 🗣️",
    "What's your biggest travel challenge that you've overcome? 💪",
    "What's the most ridiculous thing you've ever done to avoid paying for food? 🍕",
    "What's your most embarrassing moment from a beach vacation? 🏖️",
    "What's the weirdest thing you've ever done to avoid getting sick while traveling? 🤒",
    "What's your biggest travel secret that you've never told anyone? 🤫",
    "What's the most amazing view you've ever seen from a mountain? 🏔️",
    "What's your weirdest travel fear that you know is completely irrational? 😱",
    "What's the most embarrassing thing you've ever done to avoid paying for transportation? 🚌",
    "What's your biggest travel goal that you've already achieved? 🎯",
    "What's the most ridiculous thing you've ever done to avoid paying for activities? 🎪",
    "What's your most embarrassing moment from a city tour? 🏙️",
    "What's the weirdest thing you've ever done to avoid paying for souvenirs? 🎁",
    "What's your biggest travel lesson learned the hard way? 📚",
    "What's the most amazing underwater experience you've ever had? 🐠"
  ],
 
  // 'Crypto Bro': [
  //   "What's your biggest ambition in life? 🏆",
  //   "What's the most challenging obstacle you've ever overcome? ⛰️",
  //   "What's your biggest fear about failure? 😰",
  //   "What's the most courageous thing you've ever done? 💪",
  //   "What's your biggest regret about a missed opportunity? ⏳",
  //   "What's the most difficult decision you've ever made? ⚖️",
  //   "What's your biggest fear about not achieving your goals? 🎯",
  //   "What's the most challenging thing you're currently facing? 🔥",
  //   "What's your biggest fear about leadership? 👑",
  //   "What's the most ambitious thing you've ever attempted? 🚀"
  // ]
};

export const DARES = {
  'The Host': [
    "Do your best impression of a game show host for 30 seconds 🎤",
    "Sing the theme song to your favorite game show 🎵",
    "Act out a dramatic game show moment 🎭",
    "Give a motivational speech like a game show host 📢",
    "Create a new game show concept and pitch it 💡",
    "Do a game show host voice for the next 3 rounds 🎪",
    "Act out winning a million dollars on a game show 💰",
    "Give everyone a nickname like a game show host would 🏷️",
    "Create a catchphrase and use it for the rest of the game 🎯",
    "Act out being eliminated from a game show dramatically 😭",
    "Host a 2-minute 'Family Feud' style survey with the group 🎯",
    "Do a dramatic reading of a random text message as if it's a game show question 📱",
    "Create and perform a 30-second commercial for a fake product 🛒",
    "Act out being a contestant on 'The Price is Right' and guess random item prices 💰",
    "Do your best impression of a game show announcer for the next 5 minutes 🔊",
    "Create a 'Wheel of Fortune' puzzle and have the group solve it 🎡",
    "Act out being a game show contestant who's extremely nervous 😰",
    "Do a dramatic reveal of a 'secret' about someone in the room 🎭",
    "Create a fake game show called 'Truth or Dare' and pitch it to the group 🎪",
    "Act out being eliminated from a game show but then getting a 'second chance' 🎬",
    "Do your best impression of a game show host interviewing a celebrity guest 🌟",
    "Create a fake 'audience applause' sound using only your voice 👏",
    "Act out being a game show contestant who's way too confident 😎",
    "Do a dramatic reading of the room's furniture as if they're game show contestants 🪑",
    "Create a fake 'commercial break' and act out 2 different commercials 📺",
    "Act out being a game show host who's having technical difficulties 🔧",
    "Do your best impression of a game show host from a different country 🌍",
    "Create a fake 'behind the scenes' moment from a game show 🎬",
    "Act out being a game show contestant who's extremely lucky 🍀",
    "Do a dramatic reading of a random object's 'life story' as if it's a game show question 📖",
    "Create a fake 'game show reunion' and act out meeting former contestants 🤝",
    "Act out being a game show host who's secretly a contestant 🎭",
    "Do your best impression of a game show host who's extremely excited about everything 🎉",
    "Create a 1-minute weather forecast for the room using only items you can see 🌤️",
    "Do your best impression of a TikTok influencer reviewing the room's furniture 📱",
    "Act out being a food critic reviewing the snacks/drinks in the room 🍕",
    "Create a fake news report about something that happened in the room today 📰",
    "Do your best impression of a motivational speaker giving advice about cleaning 🧹",
    "Act out being a travel vlogger giving a tour of the room 🎥",
    "Create a fake product infomercial using any object in the room 🛒",
    "Do your best impression of a sports commentator calling a 'game' in the room 🏈",
    "Act out being a detective solving a mystery about a missing sock 🕵️",
    "Create a fake cooking show using only items you can find in the room 👨‍🍳",
    "Do your best impression of a teacher giving a lesson about the room's history 📚",
    "Act out being a fitness instructor leading a workout using furniture 🏃‍♂️",
    "Create a fake dating show where you interview objects in the room 💕",
    "Do your best impression of a radio DJ hosting a show about the room 🎧",
    "Act out being a scientist explaining the 'science' of why the room exists 🔬",
    "Create a fake talent show where you showcase the 'talents' of room objects 🎭",
    "Do your best impression of a therapist giving advice to the furniture 🧠",
    "Act out being a tour guide showing tourists around the room 🗺️",
    "Create a fake auction where you sell random items in the room 🎪",
    "Do your best impression of a game show contestant who's extremely unlucky 😅",
    "Act out being a superhero whose power is making everything in the room talk 🦸‍♂️",
    "Create a fake podcast episode about the room's 'history' 🎧",
    "Do your best impression of a chef reviewing the room's 'ingredients' 👨‍🍳",
    "Act out being a news anchor reporting on 'breaking news' from the room 📺",
    "Create a fake music video using only items you can find 🎵",
    "Do your best impression of a judge presiding over a 'court case' in the room ⚖️",
    "Act out being a scientist conducting experiments on room objects 🔬",
    "Create a fake documentary about the 'wildlife' in the room 🦁",
    "Do your best impression of a weather person reporting on room 'conditions' 🌤️",
    "Act out being a doctor giving a diagnosis to the room's furniture 🏥",
    "Create a fake reality show about roommates living in the room 🏠",
    "Do your best impression of a police officer investigating a 'crime' in the room 👮‍♂️",
    "Act out being a teacher giving a lesson about room 'geography' 📚",
    "Create a fake talk show where you interview room objects 🎤",
    "Do your best impression of a fortune teller reading the room's 'future' 🔮",
    "Act out being a pilot giving a safety briefing about the room ✈️",
    "Create a fake cooking competition using room items as ingredients 👨‍🍳",
    "Do your best impression of a lawyer defending a case about the room ⚖️",
    "Act out being a firefighter giving safety tips about the room 🚒",
    "Create a fake talent agency scouting 'talent' in the room 🌟",
    "Do your best impression of a librarian organizing the room's 'books' 📚",
    "Act out being a gardener giving advice about room 'plants' 🌱",
    "Create a fake beauty pageant for room objects 👑",
    "Do your best impression of a mechanic fixing 'problems' in the room 🔧",
    "Act out being a photographer taking 'fashion' photos of room items 📸",
    "Create a fake museum tour of the room's 'artifacts' 🏛️",
    "Do your best impression of a tour guide showing aliens around the room 👽",
    "Act out being a detective solving a mystery about missing socks 🕵️",
    "Create a fake sports commentary about a 'game' between room objects 🏈",
    "Do your best impression of a movie director filming a scene in the room 🎬",
    "Act out being a chef competing on a cooking show with room ingredients 👨‍🍳",
    "Create a fake beauty tutorial using room items as makeup 💄",
    "Do your best impression of a life coach giving advice about room organization 🧠",
    "Act out being a scientist explaining the 'evolution' of room furniture 🧬",
    "Create a fake game show where room objects compete for prizes 🎪",
    "Do your best impression of a therapist helping room items with their problems 🧠",
    "Act out being a teacher giving a lesson about room 'mathematics' 📐",
    "Create a fake reality show about room objects finding love 💕",
    "Do your best impression of a weather forecaster predicting room 'storms' ⛈️",
    "Act out being a doctor performing 'surgery' on broken room items 🏥",
    "Create a fake talent show where room objects showcase their 'skills' 🎭",
    "Do your best impression of a police officer giving a safety lecture 👮‍♂️",
    "Act out being a firefighter rescuing room objects from 'danger' 🚒",
    "Create a fake cooking show where you make 'dishes' from room items 👨‍🍳",
    "Do your best impression of a judge sentencing room objects for 'crimes' ⚖️",
    "Act out being a pilot flying the room to a 'destination' ✈️",
    "Create a fake documentary about the 'habitat' of room objects 🦁",
    "Do your best impression of a fortune teller predicting the room's 'future' 🔮",
    "Act out being a superhero saving the room from 'villains' 🦸‍♂️",
    "Create a fake game show where you host a competition between room items 🎤"
  ],
  // 'Just a Chill Guy': [
  //   "Do your best impression of someone in the room 👥",
  //   "Tell a joke that makes everyone laugh 😂",
  //   "Do a silly dance for 30 seconds 💃",
  //   "Make up a story on the spot 📖",
  //   "Do your best animal impression 🐾",
  //   "Act out a scene from your favorite movie 🎬",
  //   "Do a magic trick (real or fake) 🪄",
  //   "Sing a song in a funny voice 🎵",
  //   "Do your best celebrity impression 🌟",
  //   "Act out your morning routine in 30 seconds ☀️"
  // ],
  'Influencer': [
    "Sing a Taylor Swift song (or any love song) dramatically 🎤",
    "Write a short love poem on the spot 💌",
    "Act out a dramatic breakup scene 🎭",
    "Do your best Taylor Swift impression 👑",
    "Create a love story about two people in the room 💘",
    "Sing a breakup song with maximum emotion 😭",
    "Act out a romantic movie scene 🎬",
    "Write a short song about someone in the room 🎵",
    "Do a dramatic reading of a love letter 📖",
    "Act out getting proposed to 💍",
    "🤸‍♂️ Give a passionate, two-minute toast to the person to your left, celebrating their amazing qualities. Make it heartfelt!",
    "🕺 Do a slow-motion dramatic walk across the room as if you're the star of a romantic movie. Make it sizzle!",
    "🎤 Perform a dramatic reading of a random sentence from a book or magazine, but say it as if you're delivering a heartfelt love letter.",
    "🤫 Give a shoutout to your left shoe and describe its 'romantic personality.' Make it sound like it's the star of its own dating show!",
    "🗣️ Compliment every person in the room with a unique, sincere compliment. No repeats!",
    "🤪 Do a 'What's In My Bag' but use an item you have in the room instead of a bag. Get creative and make a story about it.",
    "💃 Create a new 'profile picture' for yourself using only items in the room. We need that fresh look!",
    "👑 Try on the most ridiculous outfit you can create from items in the room and do a short fashion show with a confident walk.",
    "🤸‍♀️ Do 10 lunges while describing your dream romantic getaway. Let's manifest those adventures!",
    "🤣 Recreate a famous viral dance trend from start to finish. We're talking full-out performance!",
    "🎶 Lip-sync to a song of the group's choice for 30 seconds.",
    "🗣️ Give a two-minute speech on why your favorite fictional character would make the best romantic partner.",
    "🤖 Talk like a robot for the next three rounds, but every sentence has to end with a compliment.",
    "💅 Do your best impression of another person in the room, but only using compliments.",
    "🤩 Create a secret handshake with the person to your right and perform it for the group.",
    "🎤 Sing the chorus of a song that the group chooses, but in a totally different genre.",
    "🕺 Act out a 'meet cute' with an imaginary character, making sure to show how charming you are.",
    "📸 Take a selfie with the strangest object in the room and caption it with an inspirational quote.",
    "🗣️ Make up a 'dating profile' for the person to your left, listing their best qualities and a witty bio.",
    "😂 Recite a poem you wrote in school as if it's the most romantic thing you've ever said.",
    "🎭 Act out being a famous influencer giving a tutorial on how to be confident in any situation",
    "📱 Create a fake Instagram story about the most boring thing in the room and make it exciting",
    "🎤 Do your best impression of a motivational speaker giving advice about dating",
    "💃 Create a dance routine using only furniture in the room as your dance partners",
    "🎬 Act out being a movie director filming a romantic scene between two objects in the room",
    "🎵 Create a jingle for a fake product using only items you can see in the room",
    "🎭 Act out being a therapist helping someone get over their fear of social media",
    "📺 Create a fake reality TV show trailer about the 'drama' in the room",
    "🎤 Do your best impression of a talk show host interviewing the person to your right",
    "💅 Create a fake beauty tutorial using only items you can find in the room",
    "🎭 Act out being a life coach giving advice about finding love in unexpected places",
    "📱 Create a fake TikTok trend that involves everyone in the room",
    "🎬 Act out being a casting director auditioning people for a romantic comedy",
    "🎵 Create a love song about the most random object in the room",
    "🎭 Act out being a relationship expert giving advice about modern dating",
    "📺 Create a fake commercial for a dating app that matches people with furniture",
    "🎤 Do your best impression of a radio DJ hosting a love songs hour",
    "💃 Create a fashion show using only items you can find in the room",
    "🎭 Act out being a wedding planner organizing a ceremony for two objects",
    "📱 Create a fake social media challenge that everyone has to participate in",
    "🎬 Act out being a script writer creating dialogue for a romantic scene",
    "🎵 Create a rap about the person to your left using only compliments",
    "🎭 Act out being a dating coach giving advice about first impressions",
    "📺 Create a fake game show about finding love in the room",
    "🎤 Do your best impression of a celebrity giving relationship advice",
    "💅 Create a fake lifestyle blog post about the 'magic' of the room",
    "🎭 Act out being a romance novelist reading from their latest book",
    "📱 Create a fake viral video concept that would make everyone famous",
    "🎬 Act out being a film critic reviewing a romantic movie scene",
    "🎵 Create a theme song for a fake dating reality show",
    "🎭 Act out being a relationship counselor helping two people in the room",
    "📺 Create a fake documentary about the 'mating habits' of room objects",
    "🎤 Do your best impression of a love guru giving spiritual dating advice",
    "💃 Create a fake dance competition where everyone has to participate",
    "🎭 Act out being a matchmaker trying to set up people in the room",
    "📱 Create a fake social media influencer campaign about self-love",
    "🎬 Act out being a movie producer pitching a romantic film idea",
    "🎵 Create a fake musical number about finding love in unexpected places",
    "🎭 Act out being a love therapist helping someone overcome heartbreak",
    "📺 Create a fake talk show about modern dating dilemmas",
    "🎤 Do your best impression of a famous couple giving relationship tips",
    "💅 Create a fake lifestyle magazine cover featuring someone in the room",
    "🎭 Act out being a romance expert giving advice about long-distance relationships",
    "📱 Create a fake viral challenge that promotes kindness and love",
    "🎬 Act out being a screenwriter creating a romantic comedy scene",
    "🎵 Create a fake love ballad about the room's atmosphere",
    "🎭 Act out being a relationship advisor helping someone plan a proposal",
    "📺 Create a fake reality show about finding love in unusual places",
    "🎤 Do your best impression of a love coach giving confidence advice",
    "💃 Create a fake talent show where everyone showcases their 'romantic skills'",
    "🎭 Act out being a love guru giving advice about self-confidence",
    "📱 Create a fake social media movement about spreading love and positivity"
  ],
 
  // 'Crypto Bro': [
  //   "Give an inspiring speech about conquering your fears 🗣️",
  //   "Act out leading an army into battle ⚔️",
  //   "Do your best impression of a motivational speaker 📢",
  //   "Act out achieving a great victory 🏆",
  //   "Give a speech about your biggest accomplishment 🎯",
  //   "Act out being crowned king/queen 👑",
  //   "Do your best impression of a military leader 🎖️",
  //   "Act out making a difficult decision ⚖️",
  //   "Give a speech about your life goals 🎪",
  //   "Act out being a legendary hero 🦸"
  // ],
}; 